import { StreamingServiceItem } from "../types";

const WATCHMODE_API_KEY = process.env.WATCHMODE_API_KEY!;
const WATCH_MODE_BASE_URL = "https://api.watchmode.com/v1";

/**
 * Fetch streaming services available for a specific movie based on its ID.
 *
 * This function retrieves the streaming availability for a given movie ID from the WatchMode API.
 * It returns a list of available streaming services in the US region.
 * The function assumes that the movie is available in the US region.
 *
 * @param {string} id - The unique ID of the movie for which streaming services are to be fetched.
 * @returns {Promise<StreamingServiceItem[]>} A promise that resolves to an array of streaming service items that are available for the movie.
 *          Each item contains details about the streaming service, such as the service name, type (subscription, rent, etc.), and availability.
 *
 * @throws {Error} If the fetch operation fails or the response is not valid.
 */
export async function fetchStreamingServices(
  id: string,
): Promise<StreamingServiceItem[]> {
  const availability = await fetch(
    `${WATCH_MODE_BASE_URL}/title/movie-${id}/sources/?apiKey=${WATCHMODE_API_KEY}&regions=US`,
    {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    },
  );

  return await availability.json();
  // return tempData;
}

// const tempData: StreamingServiceItem[] = [
//   {
//     source_id: 390,
//     name: "Hoopla",
//     type: "free",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://www.hoopladigital.com/title/12184106?utm_source=",
//     format: "SD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 391,
//     name: "Pluto TV",
//     type: "free",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://pluto.tv/on-demand/movies/white-chicks-2004-1-1?utm_medium=deeplink&utm_source=",
//     format: "SD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 296,
//     name: "Tubi TV",
//     type: "free",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://tubitv.com/movies/670475?utm_source=&tracking=",
//     format: "SD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 24,
//     name: "Amazon",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://watch.amazon.com/detail?gti=amzn1.dv.gti.38a9f70c-696e-be0d-8962-62c0c135ae34",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 344,
//     name: "YouTube",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.youtube.com/results?search_query=White+Chicks%2Bmovie",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 307,
//     name: "VUDU",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://athome.fandango.com/content/browse/details/White-Chicks/43259",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 349,
//     name: "AppleTV",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://tv.apple.com/us/movie/white-chicks/umc.cmc.17q42l7xxltvcxqeid455e3n1?at=1000l3V2&ct=app_tv&itscg=30200&itsct=&playableId=tvs.sbd.9001%3A271778179",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 443,
//     name: "Spectrum On Demand",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://ondemand.spectrum.net/movies/34622/white-chicks/",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 24,
//     name: "Amazon",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://watch.amazon.com/detail?gti=amzn1.dv.gti.38a9f70c-696e-be0d-8962-62c0c135ae34",
//     format: "SD",
//     price: 12.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 344,
//     name: "YouTube",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.youtube.com/results?search_query=White+Chicks%2Bmovie",
//     format: "SD",
//     price: 12.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 307,
//     name: "VUDU",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://athome.fandango.com/content/browse/details/White-Chicks/43259",
//     format: "SD",
//     price: 7.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 349,
//     name: "AppleTV",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://tv.apple.com/us/movie/white-chicks/umc.cmc.17q42l7xxltvcxqeid455e3n1?at=1000l3V2&ct=app_tv&itscg=30200&itsct=&playableId=tvs.sbd.9001%3A271778179",
//     format: "SD",
//     price: 12.99,
//     seasons: 0,
//     episodes: 0,
//   },
// ];

// const tempData2: StreamingServiceItem[] = [
//   {
//     source_id: 387,
//     name: "MAX",
//     type: "sub",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://play.max.com/show/f0a4f239-0b57-47e2-a39a-54fb96925e61?utm_source=universal_search",
//     format: "HD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 203,
//     name: "Netflix",
//     type: "sub",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://www.netflix.com/title/81602836",
//     format: "HD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 385,
//     name: "HBO (Via Hulu)",
//     type: "sub",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://www.hulu.com/watch/369cb9e5-1328-459a-87cf-86455422a304",
//     format: null,
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 307,
//     name: "VUDU",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://athome.fandango.com/content/browse/details/Dune-Part-Two/3031334",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 344,
//     name: "YouTube",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.youtube.com/results?search_query=Dune%3A+Part+Two%2Bmovie",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 443,
//     name: "Spectrum On Demand",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://ondemand.spectrum.net/movies/20913466/dune-part-two/",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 24,
//     name: "Amazon",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://watch.amazon.com/detail?gti=amzn1.dv.gti.9392c069-96f9-421b-ac7a-275308e1327a",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 349,
//     name: "AppleTV",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://tv.apple.com/us/movie/dune-part-two/umc.cmc.363aycnv6vy9qgekvew6fveb9?at=1000l3V2&ct=app_tv&itscg=30200&itsct=&playableId=tvs.sbd.9001%3A1725365997",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://www.microsoft.com/en-us/p/Dune%20Part%20Two/8D6KGWXZ0GMN",
//     format: "HD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://www.microsoft.com/en-us/p/Dune%20Part%20Two/8D6KGWXZ0GMN",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 307,
//     name: "VUDU",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://athome.fandango.com/content/browse/details/Dune-Part-Two/3031334",
//     format: "SD",
//     price: 14.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 344,
//     name: "YouTube",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.youtube.com/results?search_query=Dune%3A+Part+Two%2Bmovie",
//     format: "SD",
//     price: 14.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 24,
//     name: "Amazon",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://watch.amazon.com/detail?gti=amzn1.dv.gti.9392c069-96f9-421b-ac7a-275308e1327a",
//     format: "SD",
//     price: 14.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 349,
//     name: "AppleTV",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://tv.apple.com/us/movie/dune-part-two/umc.cmc.363aycnv6vy9qgekvew6fveb9?at=1000l3V2&ct=app_tv&itscg=30200&itsct=&playableId=tvs.sbd.9001%3A1725365997",
//     format: "SD",
//     price: 14.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://www.microsoft.com/en-us/p/Dune%20Part%20Two/8D6KGWXZ0GMN",
//     format: "HD",
//     price: 14.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://www.microsoft.com/en-us/p/Dune%20Part%20Two/8D6KGWXZ0GMN",
//     format: "SD",
//     price: 14.99,
//     seasons: 0,
//     episodes: 0,
//   },
// ];

// const tempData3: StreamingServiceItem[] = [
//   {
//     source_id: 455,
//     name: "Paramount+ with Showtime",
//     type: "sub",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.paramountplus.com/movies/beau-is-afraid/vVDK6PdmJf_s9z_uWibvkpZqiJ2TIqx8?searchReferral=publisher&source=search-feeds",
//     format: "HD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 373,
//     name: "fuboTV",
//     type: "sub",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.fubo.tv/welcome/program/MV019696430000?irmp=1206980&irad=599309",
//     format: "HD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 443,
//     name: "Spectrum On Demand",
//     type: "sub",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://ondemand.spectrum.net/movies/23818362/beau-is-afraid/",
//     format: "SD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 26,
//     name: "Prime Video",
//     type: "sub",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://watch.amazon.com/detail?gti=amzn1.dv.gti.7083d15d-a124-4e5c-8800-0cc12d3d4868&tag=",
//     format: "HD",
//     price: null,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 307,
//     name: "VUDU",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://athome.fandango.com/content/browse/details/Beau-Is-Afraid/2321129",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 344,
//     name: "YouTube",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.youtube.com/results?search_query=Beau+Is+Afraid%2Bmovie",
//     format: "SD",
//     price: 7.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 443,
//     name: "Spectrum On Demand",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url: "https://ondemand.spectrum.net/movies/23818362/beau-is-afraid/",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 349,
//     name: "AppleTV",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://tv.apple.com/us/movie/umc.cmc.ve4dsgwrfxacfhynrqho4koc?itsct=&itscg=30200&at=1010layx",
//     format: "HD",
//     price: 4.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 349,
//     name: "AppleTV",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://tv.apple.com/us/movie/umc.cmc.ve4dsgwrfxacfhynrqho4koc?itsct=&itscg=30200&at=1010layx",
//     format: "SD",
//     price: 4.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 24,
//     name: "Amazon",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://watch.amazon.com/detail?gti=amzn1.dv.gti.7083d15d-a124-4e5c-8800-0cc12d3d4868",
//     format: "SD",
//     price: 3.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.microsoft.com/en-us/p/Beau%20Is%20Afraid/8D6KGWXZGXFM",
//     format: "HD",
//     price: 5.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "rent",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.microsoft.com/en-us/p/Beau%20Is%20Afraid/8D6KGWXZGXFM",
//     format: "SD",
//     price: 4.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 307,
//     name: "VUDU",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://athome.fandango.com/content/browse/details/Beau-Is-Afraid/2321129",
//     format: "SD",
//     price: 19.98,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 344,
//     name: "YouTube",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.youtube.com/results?search_query=Beau+Is+Afraid%2Bmovie",
//     format: "SD",
//     price: 19.98,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 349,
//     name: "AppleTV",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://tv.apple.com/us/movie/umc.cmc.ve4dsgwrfxacfhynrqho4koc?itsct=&itscg=30200&at=1010layx",
//     format: "HD",
//     price: 19.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 24,
//     name: "Amazon",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://watch.amazon.com/detail?gti=amzn1.dv.gti.7083d15d-a124-4e5c-8800-0cc12d3d4868",
//     format: "SD",
//     price: 14.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.microsoft.com/en-us/p/Beau%20Is%20Afraid/8D6KGWXZGXFM",
//     format: "HD",
//     price: 7.99,
//     seasons: 0,
//     episodes: 0,
//   },
//   {
//     source_id: 398,
//     name: "Windows Store",
//     type: "buy",
//     region: "US",
//     ios_url: "Deeplinks available for paid plans only.",
//     android_url: "Deeplinks available for paid plans only.",
//     web_url:
//       "https://www.microsoft.com/en-us/p/Beau%20Is%20Afraid/8D6KGWXZGXFM",
//     format: "SD",
//     price: 7.99,
//     seasons: 0,
//     episodes: 0,
//   },
// ];
// const streamingIconMapper: { [key: string]: { name: string } } = {
//   "24": { name: "Amazon" },
//   "26": { name: "Prime Video" },
//   "203": { name: "Netflix" },
//   "296": { name: "Tubi TV" },
//   "307": { name: "VUDU" },
//   "344": { name: "YouTube" },
//   "349": { name: "AppleTV" },
//   "373": { name: "fuboTV" },
//   "385": { name: "HBO (Via Hulu)" },
//   "387": { name: "MAX" },
//   "390": { name: "Hoopla" },
//   "391": { name: "Pluto TV" },
//   "398": { name: "Windows Store" },
//   "443": { name: "Spectrum On Demand" },
//   "455": { name: "Paramount+ with Showtime" },
// };
